# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: ["tables"]

pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Mithat Gögebakan
tagline:          ''
url:              https://www.mithat.org
enforce_ssl:      www.mithat.org
shorturl:         mithatgogebakan.com

author:
  name:           'Mithat Gögebakan'
  url:            https://twitter.com/mithatgogebakan

paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           github.com/mithatgogebakan/mithatgogebakan.github.io

# This is the list of pages to include in the header of the website.
pages_list:       
  About: '/about/'
  Archive: '/archive/'
#  Feed: '/atom.xml'

# Allow URL Redirects: 
#  * https://help.github.com/articles/redirects-on-github-pages
gems:
  - jekyll-redirect-from
